### PR TITLE
Use github docker layer caching

### PR DESCRIPTION
**Pull request by kim0**

### CODE REVIEW

**Comment by kim0** [comment]
Hey @goshiz .. you might wanna give this a try. I hope refactoring is the correct branch to work on.

**Comment by kim0** [comment]
Hello @akildemir .. I'd love to understand why this was rejected, or how to make it better. I know it's a tiny contribution, but I had more tiny ones in mind :) Thanks!

**Comment by akildemir** [comment]
@goshiz

**Comment by goshiz** [comment]
Hey @kim0 it was not rejected, the source branch you've based the PR has been merged.

A will look into it, thanks.

**Comment by kim0** [comment]
Thanks @goshiz .. I've recreated it targeting develop branch at https://github.com/haven-protocol-org/haven-main/pull/12

**Pull request closed without merging**
